- hosts: all
  sudo: yes
  roles:
    - { role: common }
    - { role: geerlingguy.nodejs }
    - { role: sendmail}
    - { role: postgres, db_names: ["lab-assistant", "lab-assistant_test"] }
    - { role: vagrant }