- hosts: all
  sudo: yes
  roles:
    - { role: firewall }
    - { role: nodesource.node }
    - { role: letsencrypt, cert_contact_email: "{{ lookup('env','CERT_EMAIL') }}", cert_domain: "{{ inventory_hostname }}" }
    - { role: nginx, server_name: "{{ inventory_hostname }}", https_certs_dir: "/etc/letsencrypt/live/{{ inventory_hostname }}" }
    - { role: lab-assistant, git_sha: "{{ lookup('env', 'APP_GIT_SHA') }}", node_env: production, db_names: ["lab_assistant"], db_user: "labassistant", db_password: "{{ lookup('env','DB_PASSWORD') }}", db_host: "{{ lookup('env','DB_HOST') }}", db_port: "{{ lookup('env','DB_PORT') }}", session_secret:  "{{ lookup('env','SESSION_SECRET') }}"}
